#!/usr/bin/env zsh

eval "$_z4h_opt"

# Fork to avoid triggering https://www.zsh.org/mla/workers/2020/msg00588.html
(
  # ${(L):-I} is ı in Turkish locale.
  LC_ALL=C

  local pat hex char
  for pat in "[^A-Z]" "[A-Z]"; do
    for hex in $Z4H_PACKAGE_DIR/[[:xdigit:]][[:xdigit:]](:t); do
      printf -v char "\\x$hex"
      [[ $char == $~pat ]] || continue
      [[ -e ~/.local/share/terminfo/$hex ]] || zf_mkdir -p -- ~/.local/share/terminfo/$hex || return
      cp -- $Z4H_PACKAGE_DIR/$hex/* ~/.local/share/terminfo/$hex/ || return
      if [[ $char == [a-z] || ! ~/.local/share/terminfo/$char -ef ~/.local/share/terminfo/${(L)char}] ]]; then
        [[ -e ~/.local/share/terminfo/$char ]]                       ||
          zf_ln -s -- $hex ~/.local/share/terminfo/$char 2>/dev/null ||
          zf_mkdir -p -- ~/.local/share/terminfo/$char               ||
          return
        cp -- $Z4H_PACKAGE_DIR/$hex/* ~/.local/share/terminfo/$char/ || return
      fi
      zf_rm -rf -- $Z4H_PACKAGE_DIR/$hex || return
    done
  done
)
